$('.owl-carousel').owlCarousel({
     loop:true,
     margin:-120,
     nav:false,
     responsive:{
         0:{
             items:2
         },
         600:{
             items:3
         },
         1000:{
             items:7
         }
     }
 })